### ISSUE TITLE
Tests for v0.3 release are failing

### ISSUE THREAD

**Issue by averikitsch** [googleapis/langchain-google-memorystore-redis-python#99]
New functionality for cluster support was added in https://github.com/googleapis/langchain-google-memorystore-redis-python/pull/94; however the tests for the release candidate are timing out, see https://github.com/googleapis/langchain-google-memorystore-redis-python/pull/92; therefore blocking the release.

**Comment by murphyjacob4** [comment]
Hi, I've updated the networking infrastructure that is used to route the integration test in Cloud Build to the Memorystore instance used for testing.

I reran the most recent nightly and it seems to be succeeding now. Can we retry the test for the linked PR?

**Comment by averikitsch** [comment]
Thank you @murphyjacob4 . The tests are now passing.
